// Plain-language explanation intros behind every "?" — bilingual (FR/EN). The
// intro (what / why / takeaway) is here; the real scientific evidence (numbers +
// mini-charts) is passed per-analysis as <children> to <Explain>.
import type { Localized } from '@/i18n';
import type { ExplanationContent } from './Explain';

type E = Localized<ExplanationContent>;

export const EXPLAIN = {
  datasetOverview: {
    fr: {
      title: 'Vue d’ensemble du jeu de données',
      what: 'On affiche vos spectres, la distribution des références, une carte PCA, et la consistance des répétitions.',
      why: 'Avant tout modèle, il faut « voir » ses données : spectres aberrants, gamme de référence déséquilibrée, répétitions incohérentes.',
      takeaway: 'Regardez ces 4 vues avant de calibrer — elles évitent 80 % des mauvaises surprises.',
    },
    en: {
      title: 'Dataset overview',
      what: 'We show your spectra, the reference distribution, a PCA map, and replicate consistency.',
      why: 'Before any model, you must "see" the data: odd spectra, an unbalanced reference range, inconsistent replicates.',
      takeaway: 'Check these 4 views before calibrating — they prevent 80% of bad surprises.',
    },
  },
  addY: {
    fr: {
      title: 'Ajouter des références y',
      what: 'Chargez un fichier avec une valeur de référence par échantillon, dans l’ordre du dataset. Les cellules vides = pas encore de référence (l’échantillon reste candidat HPLC).',
      why: 'C’est le flux réel du labo : on charge les spectres, on envoie une partie en HPLC, et quand les valeurs reviennent on les ajoute ici pour (re)calibrer — sans tout ré-importer.',
      takeaway: 'Même taille que X, valeurs manquantes autorisées ; les échantillons renseignés passent en calibration.',
    },
    en: {
      title: 'Add reference values y',
      what: 'Load a file with one reference value per sample, in the dataset order. Empty cells = no reference yet (the sample stays an HPLC candidate).',
      why: 'The real lab loop: load spectra, send some to HPLC, and when the values come back add them here to (re)calibrate — without re-importing everything.',
      takeaway: 'Same size as X, missing values allowed; filled samples move into calibration.',
    },
  },
  spectra: {
    fr: {
      title: 'Graphique des spectres',
      what: 'Chaque échantillon est réduit à la moyenne de ses répétitions. La courbe épaisse est la moyenne générale ; la bande claire est l’enveloppe min–max par longueur d’onde.',
      why: 'Une courbe qui sort franchement de la bande est un spectre atypique (saturation, bulle, mauvais contact) à vérifier.',
      takeaway: 'Cherchez les courbes qui « sortent du troupeau ».',
      methods: ['mean', 'min/max band'],
    },
    en: {
      title: 'Spectra plot',
      what: 'Each sample is reduced to the mean of its replicates. The thick curve is the overall mean; the light band is the per-wavelength min–max envelope.',
      why: 'A curve clearly outside the band is an atypical spectrum (saturation, bubble, poor contact) to check.',
      takeaway: 'Look for the curves that leave the herd.',
      methods: ['mean', 'min/max band'],
    },
  },
  target: {
    fr: {
      title: 'Distribution de la référence',
      what: 'Histogramme des valeurs de référence (les y de la chimie humide) + statistiques (min / moyenne / max / écart-type).',
      why: 'Un modèle ne prédit bien que dans la gamme qu’il a vue. Une gamme étroite ou des trous annoncent des prédictions fragiles.',
      takeaway: 'Une distribution large et régulière = calibration plus robuste.',
      methods: ['histogram(20 bins)'],
    },
    en: {
      title: 'Reference distribution',
      what: 'Histogram of the reference values (the wet-chemistry y) + statistics (min / mean / max / std).',
      why: 'A model only predicts well within the range it has seen. A narrow range or gaps signal fragile predictions.',
      takeaway: 'A wide, even distribution = a more robust calibration.',
      methods: ['histogram(20 bins)'],
    },
  },
  pca: {
    fr: {
      title: 'Carte PCA',
      what: 'La PCA compresse chaque spectre (des centaines de longueurs d’onde) en 2 axes qui capturent le plus de variation. Chaque point est un échantillon, coloré par sa référence.',
      why: 'Elle révèle la structure : groupes, gradients, points isolés. Un point loin des autres est candidat à vérification.',
      details: 'Attention : 2 axes « écrasent » l’information — c’est une aide visuelle, pas une preuve. Les % = part de variation expliquée par chaque axe.',
      takeaway: 'Utile pour repérer des familles d’échantillons et des points isolés.',
      methods: ['PCA (Gram power-iteration)'],
    },
    en: {
      title: 'PCA map',
      what: 'PCA compresses each spectrum (hundreds of wavelengths) into 2 axes capturing the most variation. Each point is a sample, colored by its reference.',
      why: 'It reveals structure: clusters, gradients, isolated points. A point far from the rest is a candidate to check.',
      details: 'Caution: 2 axes "flatten" the information — a visual aid, not proof. The % = share of variation each axis explains.',
      takeaway: 'Useful to spot sample families and isolated points.',
      methods: ['PCA (Gram power-iteration)'],
    },
  },
  repetitions: {
    fr: {
      title: 'Consistance des répétitions',
      what: 'Pour chaque échantillon, distance de chacune de ses répétitions à la moyenne de l’échantillon. Une colonne = un échantillon ; ses répétitions sont empilées.',
      why: 'Deux répétitions du même échantillon devraient être quasi identiques. Une répétition loin des autres (> P95, entourée en orange) signale un problème de mesure.',
      details: 'Les lignes P75/P90/P95 sont les seuils de distance ; au-delà de P95 la répétition est jugée suspecte. Triez par « variance » pour voir les échantillons les moins reproductibles.',
      takeaway: 'Re-mesurez les répétitions suspectes avant de les intégrer.',
      methods: ['distance euclidienne à la moyenne de groupe', 'quantiles P50/75/90/95'],
    },
    en: {
      title: 'Replicate consistency',
      what: 'For each sample, the distance of each replicate to the sample mean. One column = one sample; its replicates are stacked.',
      why: 'Two replicates of the same sample should be nearly identical. A replicate far from the others (> P95, ringed in orange) signals a measurement problem.',
      details: 'The P75/P90/P95 lines are distance thresholds; above P95 the replicate is flagged suspect. Sort by "variance" to see the least reproducible samples.',
      takeaway: 'Re-measure suspect replicates before integrating them.',
      methods: ['euclidean distance to group mean', 'quantiles P50/75/90/95'],
    },
  },
  healthScore: {
    fr: {
      title: 'Score de santé des données',
      what: 'On agrège les constats qualité en une note sur 100 : chaque point bloquant retire 20, chaque avertissement 6.',
      why: 'Une note simple pour décider en un coup d’œil si les données sont prêtes ou s’il faut d’abord corriger.',
      details: 'Règle volontairement simple et explicable — pas de boîte noire. Le détail de chaque constat montre la mesure qui l’a déclenché.',
      takeaway: 'Traitez les points 🔴 avant de calibrer.',
    },
    en: {
      title: 'Data health score',
      what: 'We aggregate quality findings into a score out of 100: each blocking issue removes 20, each warning 6.',
      why: 'A simple score to decide at a glance whether the data is ready or needs fixing first.',
      details: 'A deliberately simple, explainable rule — no black box. Each finding’s detail shows the metric that triggered it.',
      takeaway: 'Handle the 🔴 items before calibrating.',
    },
  },
  healthSpectra: {
    fr: {
      title: 'Spectres — problématiques en rouge',
      what: 'Les bandes montrent la dispersion des spectres SAINS (quantiles). Les spectres jugés problématiques — saturés, plats, ou atypiques (T²/Q) — sont surdessinés en rouge.',
      why: 'On repère d’un coup d’œil les spectres à re-mesurer ou écarter : une ligne rouge qui décolle des bandes = un spectre anormal (saturation, bulle, mauvais contact).',
      takeaway: 'Les lignes rouges hors des bandes sont à vérifier avant de calibrer.',
    },
    en: {
      title: 'Spectra — problematic in red',
      what: 'The bands show the spread of the HEALTHY spectra (quantiles). Spectra flagged as problematic — saturated, flat, or atypical (T²/Q) — are overdrawn in red.',
      why: 'You spot at a glance the spectra to re-measure or drop: a red line leaving the bands = an abnormal spectrum (saturation, bubble, poor contact).',
      takeaway: 'Red lines outside the bands should be checked before calibrating.',
    },
  },
  healthPca: {
    fr: {
      title: 'PCA — problématiques en rouge',
      what: 'Chaque point est un échantillon projeté sur 2 axes PCA ; les spectres problématiques sont en rouge.',
      why: 'Les points rouges isolés du nuage confirment visuellement les atypies détectées (T²/Q, saturation) — une aide, pas une preuve (2 axes écrasent l’information).',
      takeaway: 'Un point rouge à l’écart = un spectre franchement différent des autres.',
      methods: ['PCA (Gram power-iteration)'],
    },
    en: {
      title: 'PCA — problematic in red',
      what: 'Each point is a sample projected onto 2 PCA axes; problematic spectra are in red.',
      why: 'Red points away from the cloud visually confirm the detected atypicalities (T²/Q, saturation) — an aid, not proof (2 axes flatten the info).',
      takeaway: 'A red point off to the side = a spectrum clearly different from the rest.',
      methods: ['PCA (Gram power-iteration)'],
    },
  },
  splitRecommendation: {
    fr: {
      title: 'Recommandation de découpage',
      what: 'On détecte si vos données sont structurées par une métadonnée (ici l’instrument) et on découpe en conséquence (GroupKFold).',
      why: 'Si des répétitions ou un même instrument sont à la fois en apprentissage et en test, le test « triche » (fuite) et surestime la performance.',
      takeaway: 'Le découpage se fait par échantillon/instrument, jamais au hasard rangée par rangée.',
      methods: ['GroupKFold', 'sample_id grouping'],
    },
    en: {
      title: 'Split recommendation',
      what: 'We detect whether your data is structured by a metadata (here the instrument) and split accordingly (GroupKFold).',
      why: 'If replicates or one instrument appear in both training and test, the test "cheats" (leakage) and overstates performance.',
      takeaway: 'Splitting is by sample/instrument, never randomly row by row.',
      methods: ['GroupKFold', 'sample_id grouping'],
    },
  },
  hplcSelection: {
    fr: {
      title: 'Sélection des échantillons pour l’HPLC',
      what: 'Sous votre budget, on choisit des échantillons variés et représentatifs (sélection diversifiante), et on écarte les outliers forts vers une vérification.',
      why: 'La chimie humide coûte cher : on veut les échantillons qui apportent le plus d’information, pas les plus extrêmes. Un outlier n’est pas forcément un bon candidat.',
      details: 'Version actuelle : Kennard-Stone / SPXY (diversification géométrique). La méthode D-optimal (optimisation du volume d’information) est en cours d’ajout dans le moteur natif.',
      takeaway: 'On sélectionne des candidats informatifs, puis on vérifie leur atypie avant de les envoyer.',
      methods: ['Kennard-Stone', 'SPXY', '→ D-optimal (à venir)'],
    },
    en: {
      title: 'Choosing samples for HPLC',
      what: 'Within your budget, we pick varied, representative samples (diversifying selection) and hold back strong outliers for review.',
      why: 'Wet chemistry is expensive: we want the most informative samples, not the most extreme. An outlier isn’t necessarily a good candidate.',
      details: 'Current version: Kennard-Stone / SPXY (geometric diversification). D-optimal (information-volume optimization) is being added to the native engine.',
      takeaway: 'We pick informative candidates, then check their atypicality before sending them.',
      methods: ['Kennard-Stone', 'SPXY', '→ D-optimal (coming)'],
    },
  },
  enrichmentReasons: {
    fr: {
      title: 'Colonne « Pourquoi choisi »',
      what: 'Pour chaque candidat, une étiquette en langage clair explique ce qu’il apporte au modèle. Ce n’est pas un défaut de l’échantillon : c’est la raison pour laquelle le mesurer en HPLC est utile.',
      why: 'On ne choisit pas au hasard ni « les plus extrêmes » : on choisit ceux qui comblent ce qui manque au modèle. L’étiquette dit quel manque chacun comble.',
      takeaway: 'Ensemble, ces candidats couvrent au mieux la diversité de vos échantillons.',
    },
    en: {
      title: '"Why chosen" column',
      what: 'For each candidate, a plain-language tag says what it brings to the model. It is not a flaw of the sample: it is why measuring it by HPLC is worthwhile.',
      why: 'We don’t pick at random or "the most extreme": we pick those that fill what the model is missing. The tag says which gap each one fills.',
      takeaway: 'Together, these candidates best cover the diversity of your samples.',
    },
  },
  infoScore: {
    fr: {
      title: 'Score d’information (distance au domaine)',
      what: 'Pour chaque échantillon candidat, on mesure la distance de son spectre au « nuage » des échantillons déjà calibrés, en unités d’écart-type (σ) sur une carte PCA.',
      why: 'Plus un échantillon est loin de ce que le modèle connaît, plus le mesurer en HPLC apporte d’information nouvelle. C’est le critère de sélection : on classe les candidats par score décroissant.',
      details: 'Score ≈ 0 σ : très proche du connu (peu informatif). 1–3 σ : informatif, il étend ou densifie la couverture. > 3 σ : très atypique → possible artefact, basculé en « à vérifier » (règle d’or). La barre colorée = score relatif au plus élevé du lot.',
      takeaway: 'Un score élevé = candidat informatif ; un score extrême (> 3 σ) = à vérifier d’abord.',
      methods: ['PCA conjointe (candidats + calibration)', 'distance en σ au centroïde'],
    },
    en: {
      title: 'Information score (distance to domain)',
      what: 'For each candidate sample we measure its spectrum’s distance to the "cloud" of already-calibrated samples, in standard-deviation (σ) units on a PCA map.',
      why: 'The further a sample is from what the model knows, the more new information measuring it by HPLC brings. That’s the selection criterion: candidates are ranked by decreasing score.',
      details: 'Score ≈ 0 σ: very close to the known (little info). 1–3 σ: informative, it extends or densifies coverage. > 3 σ: very atypical → possible artifact, flipped to "to check" (golden rule). The colored bar = score relative to the batch max.',
      takeaway: 'A high score = an informative candidate; an extreme score (> 3 σ) = check it first.',
      methods: ['joint PCA (candidates + calibration)', 'σ distance to centroid'],
    },
  },
  safetyFlag: {
    fr: {
      title: 'Colonne « Sécurité » — que signifie « À vérifier » ?',
      what: 'Chaque candidat porte un drapeau : 🟢 Sûr à envoyer, ou 🟠 À vérifier.',
      why: '🟠 « À vérifier » = le spectre de cet échantillon a été repéré comme fortement atypique (outlier / hors-domaine). Ça peut être un vrai échantillon rare… ou juste un défaut de mesure (saturation, bulle, mauvais contact). Avant de payer une analyse HPLC, on demande de le re-vérifier (re-mesurer / inspecter le spectre).',
      details: 'Règle d’or du produit : on sélectionne des échantillons INFORMATIFS, pas des outliers. Un outlier fort n’est donc jamais envoyé automatiquement — il est mis de côté en « À vérifier ». Le bouton « Exporter la liste HPLC » n’envoie que les 🟢 ; les 🟠 restent en attente de votre contrôle.',
      takeaway: '🟢 = envoyez. 🟠 = re-vérifiez d’abord (possible artefact), ne payez pas l’HPLC à l’aveugle.',
    },
    en: {
      title: '"Safety" column — what does "To check" mean?',
      what: 'Each candidate carries a flag: 🟢 Safe to send, or 🟠 To check.',
      why: '🟠 "To check" = this sample’s spectrum was flagged as strongly atypical (outlier / out-of-domain). It may be a genuinely rare sample… or just a measurement artifact (saturation, bubble, poor contact). Before paying for an HPLC analysis, we ask you to re-check it (re-measure / inspect the spectrum).',
      details: 'The product’s golden rule: we select INFORMATIVE samples, not outliers. A strong outlier is therefore never auto-sent — it is held back as "To check". The "Export HPLC worklist" button only sends the 🟢 ones; the 🟠 wait for your review.',
      takeaway: '🟢 = send. 🟠 = re-check first (possible artifact), don’t pay for HPLC blindly.',
    },
  },
  selectionSpectra: {
    fr: {
      title: 'Spectres sélectionnés',
      what: 'Les bandes montrent la dispersion des spectres de calibration par longueur d’onde (quantiles P10–P90 et P25–P75, plus la médiane). Les lignes ambre sont les spectres des échantillons retenus au budget.',
      why: 'On voit directement si les candidats retenus « sortent » de l’enveloppe connue : des lignes ambre qui débordent des bandes = des spectres nouveaux (informatifs) à envoyer à l’HPLC.',
      takeaway: 'Des lignes ambre hors des bandes = de l’information nouvelle pour le modèle.',
    },
    en: {
      title: 'Selected spectra',
      what: 'The bands show the spread of the calibration spectra per wavelength (P10–P90 and P25–P75 quantiles, plus the median). The amber lines are the spectra of the budget-selected samples.',
      why: 'You see directly whether the selected candidates fall outside the known envelope: amber lines spilling past the bands = new (informative) spectra worth sending to HPLC.',
      takeaway: 'Amber lines outside the bands = new information for the model.',
    },
  },
  selectionPca: {
    fr: {
      title: 'Carte d’enrichissement (PCA)',
      what: 'Une PCA place la calibration (gris) et les candidats (teal) sur 2 axes. Les échantillons retenus au budget sont en ambre.',
      why: 'C’est le cœur pédagogique de la sélection : on voit que les candidats retenus « remplissent les coins vides » autour du nuage de calibration — ils étendent la couverture du modèle.',
      details: 'La sélection classe les candidats par distance au domaine connu ; augmenter le budget ajoute les points ambre du plus au moins informatif. 2 axes écrasent l’information (aide visuelle).',
      takeaway: 'Les points ambre aux bords/coins = les plus utiles à mesurer.',
      methods: ['PCA conjointe', 'distance au domaine'],
    },
    en: {
      title: 'Enrichment map (PCA)',
      what: 'A PCA places the calibration (grey) and the candidates (teal) on 2 axes. The budget-selected samples are amber.',
      why: 'This is the pedagogical heart of selection: you see the selected candidates "fill the empty corners" around the calibration cloud — they extend the model’s coverage.',
      details: 'Selection ranks candidates by distance to the known domain; increasing the budget adds amber points from most to least informative. 2 axes flatten the information (a visual aid).',
      takeaway: 'Amber points at the edges/corners = the most useful to measure.',
      methods: ['joint PCA', 'distance to domain'],
    },
  },
  budgetRecommendation: {
    fr: {
      title: 'Combien d’échantillons envoyer ?',
      what: 'L’app propose un nombre : les candidats dont le score d’information dépasse ~0,75 σ, c’est-à-dire ceux qui étendent réellement le domaine du modèle.',
      why: 'Les candidats sont classés du plus au moins informatif. Passé la recommandation, les suivants ressemblent de plus en plus à la calibration : chaque envoi supplémentaire coûte de l’HPLC pour un gain d’information décroissant.',
      details: 'Le curseur n’est PAS bridé : vous pouvez descendre à 1 ou monter jusqu’à la totalité du pool. La recommandation n’est qu’un point de départ justifié (repère ambre sur le curseur).',
      takeaway: 'Suivez la reco pour le meilleur rapport information/coût, ou ajustez selon votre budget réel.',
      methods: ['score d’information (distance au domaine)', 'seuil 0,75 σ'],
    },
    en: {
      title: 'How many samples to send?',
      what: 'The app proposes a count: the candidates whose information score exceeds ~0.75 σ, i.e. those that genuinely extend the model’s domain.',
      why: 'Candidates are ranked most- to least-informative. Past the recommendation, the next ones increasingly resemble the calibration: each extra send costs HPLC for a diminishing information gain.',
      details: 'The slider is NOT capped: you can go down to 1 or up to the whole pool. The recommendation is only a justified starting point (amber tick on the slider).',
      takeaway: 'Follow the rec. for the best information/cost ratio, or adjust to your real budget.',
      methods: ['information score (distance to domain)', '0.75 σ threshold'],
    },
  },
  reliabilityMix: {
    fr: {
      title: 'Répartition des fiabilités',
      what: 'Sur le lot prédit, part de chaque feu : 🟢 fiable, 🟠 prudence, 🔴 hors-domaine, 🔵 informatif.',
      why: 'Vue d’ensemble de la confiance du lot : beaucoup de 🔴/🟠 = le lot s’éloigne de ce que le modèle connaît (dérive, nouveau type).',
      takeaway: 'Un lot sain est majoritairement 🟢 ; surveillez la montée des 🔴.',
    },
    en: {
      title: 'Reliability breakdown',
      what: 'Across the predicted batch, the share of each light: 🟢 reliable, 🟠 caution, 🔴 out-of-domain, 🔵 informative.',
      why: 'A batch-level view of confidence: many 🔴/🟠 = the batch drifts from what the model knows (drift, new type).',
      takeaway: 'A healthy batch is mostly 🟢; watch a rising share of 🔴.',
    },
  },
  maintenanceModelSpace: {
    fr: {
      title: 'Renvoi HPLC dans l’espace du modèle',
      what: 'On fait prédire le nouveau lot par le modèle de calibration déployé, puis on classe les échantillons à renvoyer en chimie humide selon deux signaux du modèle : spectre hors-domaine (X, la PLS/Ridge ne « reconnaît » pas ce spectre) et prédiction hors de la gamme apprise (Y, extrapolation).',
      why: 'Re-mesurer au hasard gaspille le budget HPLC. Les échantillons que le modèle prédit mal (hors-X ou hors-Y) sont ceux dont la vraie valeur apporterait le plus à la prochaine calibration.',
      takeaway: 'Renvoyez d’abord le haut de la liste : ce sont les points qui étendent le domaine du modèle.',
      methods: ['prédiction du modèle', 'domaine d’applicabilité (X)', 'extrapolation Y'],
    },
    en: {
      title: 'HPLC re-send in the model space',
      what: 'The deployed calibration model predicts the new batch, then samples to re-send are ranked by two model signals: spectrum out-of-domain (X, the PLS/Ridge does not "recognize" it) and prediction outside the learned range (Y, extrapolation).',
      why: 'Random re-measurement wastes the HPLC budget. The samples the model predicts worst (out-X or out-Y) are the ones whose true value would help the next calibration most.',
      takeaway: 'Re-send the top of the list first: those are the points that extend the model’s domain.',
      methods: ['model prediction', 'applicability domain (X)', 'Y extrapolation'],
    },
  },
  preprocessingPreview: {
    fr: {
      title: 'Aperçu préprocessing',
      what: 'Applique une correction classique à TOUS les spectres pour les visualiser : SNV (normalise chaque spectre), 1re/2de dérivée (Savitzky-Golay, enlève la ligne de base et révèle les pics), MSC (corrige la diffusion), Std scaler (centre-réduit chaque bande).',
      why: 'Les spectres bruts se ressemblent tous ; après préprocessing les différences chimiques deviennent visibles. C’est aussi ce que la calibration teste en interne.',
      takeaway: 'Aperçu visuel seulement : les données brutes ne changent pas. Le choix est partagé avec « Santé des données ».',
      methods: ['SNV', 'Savitzky-Golay', 'MSC', 'StandardScaler'],
    },
    en: {
      title: 'Preprocessing preview',
      what: 'Applies a classic correction to ALL spectra for viewing: SNV (normalizes each spectrum), 1st/2nd derivative (Savitzky-Golay, removes baseline and reveals peaks), MSC (scatter correction), Std scaler (centers/scales each band).',
      why: 'Raw spectra all look alike; after preprocessing the chemical differences become visible. It is also what calibration screens internally.',
      takeaway: 'Visual preview only: the raw data does not change. The choice is shared with "Data health".',
      methods: ['SNV', 'Savitzky-Golay', 'MSC', 'StandardScaler'],
    },
  },
  repMode: {
    fr: {
      title: 'Répétitions pour la calibration',
      what: 'Comment les répétitions d’un même échantillon alimentent le modèle : « moyenne par échantillon » (une ligne = le spectre moyen) ou « répétitions brutes » (une ligne par répétition, même référence y).',
      why: 'La moyenne est robuste au bruit de mesure ; les répétitions brutes gardent la variabilité inter-répétitions (utile si l’instrument est bruité, mais risque de sur-représenter les échantillons très répétés).',
      takeaway: 'Défaut = moyenne. Changer ce réglage réinitialise le modèle (les lignes d’apprentissage changent).',
    },
    en: {
      title: 'Replicates for calibration',
      what: 'How a sample’s replicates feed the model: "per-sample mean" (one row = the mean spectrum) or "raw replicates" (one row per replicate, same reference y).',
      why: 'The mean is robust to measurement noise; raw replicates keep replicate variability (useful for a noisy instrument, but can over-represent heavily-replicated samples).',
      takeaway: 'Default = mean. Changing this resets the model (the training rows change).',
    },
  },
  predictionAlerts: {
    fr: {
      title: 'Alertes par échantillon',
      what: 'Trois garde-fous indépendants sur chaque prédiction : Extrapolation (hors Y) = la valeur prédite sort de la gamme des références apprises ; Conformal (densité Y) = peu de références au niveau prédit, l’intervalle est donc peu fiable ; Distance spectrale (hors X) = le spectre est loin du nuage de calibration.',
      why: 'Une prédiction peut être fausse pour des raisons différentes : hors gamme en Y, dans un « trou » de références, ou avec un spectre inconnu en X. Les séparer dit quoi faire (re-mesurer, envoyer en chimie, enrichir).',
      details: 'Hors Y : prédiction < min ou > max des références (bordure = 5 % des bords). Densité Y : part de références à ± 0,5 σ_y du prédit (peu couvert < 10 %, quasi isolé < 3 %). Hors X : distance au domaine en σ (bordure ≥ 2, hors-domaine ≥ 3). Seuils configurables par méthode validée.',
      takeaway: 'Un point vert sur les trois colonnes est sûr ; une alerte rouge oriente vers un contrôle chimie.',
      methods: ['extrapolation Y', 'densité conformal (Y)', 'domaine d’applicabilité (T²/Q)'],
    },
    en: {
      title: 'Per-sample alerts',
      what: 'Three independent guards on each prediction: Extrapolation (out-Y) = the predicted value leaves the learned reference range; Conformal (Y-density) = few references at the predicted level, so the interval is unreliable; Spectral distance (out-X) = the spectrum is far from the calibration cloud.',
      why: 'A prediction can be wrong for different reasons: out of Y range, in a reference "gap", or with an unknown X spectrum. Separating them tells you what to do (re-measure, send to chemistry, enrich).',
      details: 'Out-Y: prediction < min or > max of references (edge = 5 % margins). Y-density: share of references within ± 0.5 σ_y of the prediction (sparse < 10 %, near-isolated < 3 %). Out-X: distance to domain in σ (edge ≥ 2, out-of-domain ≥ 3). Thresholds configurable per validated method.',
      takeaway: 'A green dot across all three columns is safe; a red alert points to a chemistry check.',
      methods: ['Y extrapolation', 'conformal density (Y)', 'applicability domain (T²/Q)'],
    },
  },
  predictionHistogram: {
    fr: {
      title: 'Distribution des valeurs prédites',
      what: 'Histogramme des valeurs prédites du lot, avec la gamme apprise (min–max des références) surlignée.',
      why: 'Des prédictions qui débordent de la gamme apprise sont des extrapolations : le modèle « invente » hors de ce qu’il a vu.',
      takeaway: 'Les barres hors de la zone surlignée sont à regarder de près.',
      methods: ['histogram(16 bins)'],
    },
    en: {
      title: 'Predicted-value distribution',
      what: 'Histogram of the batch’s predicted values, with the learned range (reference min–max) highlighted.',
      why: 'Predictions spilling past the learned range are extrapolations: the model "guesses" beyond what it saw.',
      takeaway: 'Bars outside the highlighted zone deserve a closer look.',
      methods: ['histogram(16 bins)'],
    },
  },
  domainMap: {
    fr: {
      title: 'Carte du domaine d’applicabilité',
      what: 'Chaque prédiction est placée selon sa distance au domaine connu (axe X) et la largeur de son intervalle (axe Y), colorée par son feu.',
      why: 'C’est le « pourquoi » des couleurs : à droite des lignes, l’échantillon s’éloigne trop du domaine appris → prudence puis hors-domaine.',
      details: 'Ligne « bordure » = seuil 🟠 (score ≥ 1) ; ligne « hors-domaine » = seuil 🔴 (score ≥ 2). Ces seuils sont configurables par méthode validée.',
      takeaway: 'Plus un point est à droite, moins la prédiction est fiable.',
      methods: ['domaine d’applicabilité (T²/Q/kNN)'],
    },
    en: {
      title: 'Applicability-domain map',
      what: 'Each prediction is placed by its distance to the known domain (X axis) and its interval width (Y axis), colored by its light.',
      why: 'This is the "why" of the colors: right of the lines, the sample drifts too far from the learned domain → caution then out-of-domain.',
      details: '"Border" line = 🟠 threshold (score ≥ 1); "out-of-domain" line = 🔴 threshold (score ≥ 2). These thresholds are configurable per validated method.',
      takeaway: 'The further right a point, the less reliable the prediction.',
      methods: ['applicability domain (T²/Q/kNN)'],
    },
  },
  calibrationChooser: {
    fr: {
      title: 'Choisir & comparer les pipelines',
      what: 'Vous cochez plusieurs pipelines (préprocessing + modèle) ; chacun est entraîné et évalué sur le même test gelé, puis classé.',
      why: 'Il n’existe pas un « meilleur » préprocessing universel : ça dépend de vos spectres. Comparer plusieurs recettes évite de se contenter d’un PLS brut sous-optimal.',
      details: 'Les PLS tournent sur le vrai moteur libn4m (WASM) ; Ridge et AOM-Ridge sur un solveur numérique honnête embarqué. Chaque pipeline balaie son réglage (composantes, α, ou opérateur) et garde le meilleur.',
      takeaway: 'Cochez une petite matrice, lancez, et laissez le classement désigner le gagnant.',
      methods: ['PLS (libn4m WASM)', 'Ridge (closed-form)', 'AOM (screen+select)'],
    },
    en: {
      title: 'Choose & compare pipelines',
      what: 'You tick several pipelines (preprocessing + model); each is trained and scored on the same frozen test, then ranked.',
      why: 'There is no universal "best" preprocessing — it depends on your spectra. Comparing recipes avoids settling for a sub-optimal raw PLS.',
      details: 'PLS runs on the real libn4m engine (WASM); Ridge and AOM-Ridge on an honest embedded numeric solver. Each pipeline sweeps its setting (components, α, or operator) and keeps the best.',
      takeaway: 'Tick a small matrix, run, and let the leaderboard name the winner.',
      methods: ['PLS (libn4m WASM)', 'Ridge (closed-form)', 'AOM (screen+select)'],
    },
  },
  cartesianMatrix: {
    fr: {
      title: 'Cartésien — la matrice de préprocessing',
      what: 'On combine une étape de diffusion {aucune, SNV} et une étape de dérivée {aucune, lissage, 1re, 2de} : le produit cartésien donne toutes les combinaisons, chacune testée avec le modèle (PLS ou Ridge).',
      why: 'Le meilleur préprocessing dépend des spectres. Plutôt que de le deviner, on essaie la grille entière et on garde la meilleure case sur le test gelé.',
      details: 'PLS tourne sur le vrai moteur libn4m (WASM) ; Ridge sur un solveur closed-form honnête (XᵀX + αI)⁻¹Xᵀy exécuté dans le navigateur. L’onglet « RMSE vs réglage » montre la RMSE de chaque combinaison.',
      takeaway: 'La case gagnante = la combinaison préprocessing la mieux adaptée à vos données.',
      methods: ['produit cartésien', 'PLS (WASM) / Ridge (closed-form)'],
    },
    en: {
      title: 'Cartesian — the preprocessing matrix',
      what: 'We combine a scatter stage {none, SNV} and a derivative stage {none, smooth, 1st, 2nd}: the Cartesian product yields every combination, each tested with the model (PLS or Ridge).',
      why: 'The best preprocessing depends on the spectra. Instead of guessing, we try the whole grid and keep the best cell on the frozen test.',
      details: 'PLS runs on the real libn4m engine (WASM); Ridge on an honest closed-form solver (XᵀX + αI)⁻¹Xᵀy run in the browser. The "RMSE vs setting" tab shows each combination’s RMSE.',
      takeaway: 'The winning cell = the preprocessing combination best suited to your data.',
      methods: ['Cartesian product', 'PLS (WASM) / Ridge (closed-form)'],
    },
  },
  aomVariants: {
    fr: {
      title: 'AOM — sélection automatique du préprocessing',
      what: 'AOM essaie un banc de préprocessings (brut / SNV / dérivées / detrend), ajuste le modèle sur chacun et retient automatiquement celui qui prédit le mieux.',
      why: 'Cela automatise le choix du préprocessing — souvent le levier le plus important — au lieu de le deviner. AOM-PLS pilote un PLS ; AOM-Ridge un Ridge.',
      details: 'Version compacte du principe AOM (screening d’opérateurs stricts-linéaires + sélection). La version complète (banc étendu, sélection par covariance) vit dans le moteur natif nirs4all-methods/aom.',
      takeaway: 'Un bon point de départ « je ne sais pas quel préprocessing choisir ».',
      methods: ['screen d’opérateurs', 'sélection sur test'],
    },
    en: {
      title: 'AOM — automatic preprocessing selection',
      what: 'AOM tries a bank of preprocessings (raw / SNV / derivatives / detrend), fits the model on each and automatically keeps the one that predicts best.',
      why: 'It automates the preprocessing choice — often the biggest lever — instead of guessing it. AOM-PLS drives a PLS; AOM-Ridge a Ridge.',
      details: 'A compact form of the AOM idea (strict-linear operator screening + selection). The full version (extended bank, covariance selection) lives in the native nirs4all-methods/aom engine.',
      takeaway: 'A good "I don’t know which preprocessing to pick" starting point.',
      methods: ['operator screen', 'select on test'],
    },
  },
  leaderboard: {
    fr: {
      title: 'Classement des pipelines',
      what: 'Chaque pipeline coché est évalué sur un jeu de test gelé (jamais vu à l’entraînement) et classé par RMSE croissant.',
      why: 'Le test gelé donne une estimation honnête de l’erreur en routine — pas l’erreur optimiste sur les données d’entraînement.',
      details: 'RMSE = erreur typique (plus bas = mieux). R² = variation expliquée. RPD / RPIQ = étalement des références ÷ erreur (plus haut = mieux ; RPD > 2 ≈ criblage, > 3 ≈ quantification). Cliquez une ligne pour voir ses graphiques.',
      takeaway: 'Le 🏆 est le meilleur compromis ; regardez aussi RPD/RPIQ, pas seulement la RMSE.',
      methods: ['RMSE', 'R²', 'RPD', 'RPIQ'],
    },
    en: {
      title: 'Pipeline leaderboard',
      what: 'Each ticked pipeline is scored on a frozen test set (never seen in training) and ranked by increasing RMSE.',
      why: 'The frozen test gives an honest estimate of routine error — not the optimistic error on training data.',
      details: 'RMSE = typical error (lower = better). R² = variation explained. RPD / RPIQ = reference spread ÷ error (higher = better; RPD > 2 ≈ screening, > 3 ≈ quantification). Click a row to see its charts.',
      takeaway: 'The 🏆 is the best trade-off; also read RPD/RPIQ, not just RMSE.',
      methods: ['RMSE', 'R²', 'RPD', 'RPIQ'],
    },
  },
  modelReport: {
    fr: {
      title: 'Bulletin du modèle',
      what: 'On construit le modèle et on le note : « assez bon pour du criblage ou de la quantification ? » selon des seuils (RPD/RPIQ) configurables par méthode.',
      why: 'Traduire des métriques statistiques en une décision d’usage concrète pour le labo.',
      details: 'RMSEP = erreur typique de prédiction. R² = part de variation expliquée. RPD/RPIQ = rapport de l’étalement des références à l’erreur : plus c’est haut, mieux c’est. Le détail montre la composition du pipeline et les résultats d’entraînement (observé vs prédit, résidus).',
      takeaway: 'La couleur du bulletin dit l’usage autorisé ; les chiffres disent pourquoi.',
      methods: ['RMSEP', 'R²', 'RPD', 'RPIQ', 'bias'],
    },
    en: {
      title: 'Model report card',
      what: 'We build the model and grade it: "good enough for screening or quantification?" against per-method thresholds (RPD/RPIQ).',
      why: 'Turning statistical metrics into a concrete usage decision for the lab.',
      details: 'RMSEP = typical prediction error. R² = share of variation explained. RPD/RPIQ = ratio of reference spread to error: higher is better. The detail shows the pipeline composition and training results (observed vs predicted, residuals).',
      takeaway: 'The card color states the authorized use; the numbers say why.',
      methods: ['RMSEP', 'R²', 'RPD', 'RPIQ', 'bias'],
    },
  },
  maintenanceDrift: {
    fr: {
      title: 'Surveiller la dérive du modèle',
      what: 'On compare un nouveau lot de spectres de routine à la population de calibration, et on mesure la part qui sort du domaine connu du modèle.',
      why: 'Avec le temps, les échantillons changent (saison, site, instrument). Un modèle NIRS ne reste fiable que sur ce qui ressemble à sa calibration ; détecter la dérive tôt évite de rendre de mauvais résultats.',
      details: 'La « dérive » est isolée par une PCA conjointe (calibration + nouveau lot) : les nouveaux points loin du nuage de calibration sont hors-domaine. Selon leur proportion, on recommande de surveiller, ré-échantillonner (HPLC) ou ré-entraîner / transférer.',
      takeaway: 'Ajoutez régulièrement un lot ; agissez quand la part hors-domaine grimpe.',
      methods: ['PCA conjointe', 'nouveauté (distance au domaine)'],
    },
    en: {
      title: 'Monitor model drift',
      what: 'We compare a new batch of routine spectra to the calibration population and measure the share that leaves the model’s known domain.',
      why: 'Over time samples change (season, site, instrument). A NIRS model only stays reliable on what resembles its calibration; catching drift early prevents releasing bad results.',
      details: 'Drift is isolated with a joint PCA (calibration + new batch): new points far from the calibration cloud are out of domain. Depending on their proportion, we recommend monitoring, resampling (HPLC), or retraining / transfer.',
      takeaway: 'Add a batch regularly; act when the out-of-domain share climbs.',
      methods: ['joint PCA', 'novelty (distance to domain)'],
    },
  },
  driftMap: {
    fr: {
      title: 'Carte de dérive (PCA)',
      what: 'Une PCA conjointe place la calibration (gris) et le nouveau lot sur les 2 mêmes axes. Les nouveaux points en vert sont dans le domaine, en rouge ils en sortent (dérive).',
      why: 'Voir « où » tombe le nouveau lot par rapport à ce que le modèle connaît rend la dérive intuitive : un amas rouge à l’écart = un nouveau type ou un nouvel instrument.',
      details: 'Un nouveau point est jugé hors-domaine si sa distance au nuage de calibration dépasse 2,5 écarts-types (en unités de PC). Comme partout, 2 axes écrasent l’information — c’est une aide visuelle.',
      takeaway: 'Des points rouges groupés à l’écart = dérige structurée à traiter.',
      methods: ['PCA conjointe', 'seuil de nouveauté 2.5σ'],
    },
    en: {
      title: 'Drift map (PCA)',
      what: 'A joint PCA places the calibration (grey) and the new batch on the same 2 axes. New points in teal are in domain, in red they leave it (drift).',
      why: 'Seeing "where" the new batch falls versus what the model knows makes drift intuitive: a red cluster off to the side = a new type or a new instrument.',
      details: 'A new point is out of domain if its distance to the calibration cloud exceeds 2.5 standard deviations (in PC units). As always, 2 axes flatten the information — it’s a visual aid.',
      takeaway: 'A clustered red group off to the side = structured drift to handle.',
      methods: ['joint PCA', 'novelty threshold 2.5σ'],
    },
  },
  reliability: {
    fr: {
      title: 'Fiabilité d’une prédiction',
      what: 'Chaque prédiction reçoit un feu : 🟢 fiable, 🟠 prudence, 🔴 hors-domaine, 🔵 informatif à mesurer.',
      why: 'Un modèle NIRS n’est fiable que sur des échantillons ressemblant à ceux appris. La couleur relie un diagnostic (domaine, incertitude) à une action autorisée.',
      details: 'On combine la distance au domaine connu (T²/Q) et la largeur de l’intervalle. La « fiabilité » forte (intervalle conforme validé) arrive avec le conformal natif.',
      takeaway: 'Ne rendez jamais un 🔴 ; un 🔵 vaut la peine d’être mesuré.',
      methods: ['domaine d’applicabilité (T²/Q/kNN)', '→ conformal (à venir)'],
    },
    en: {
      title: 'Prediction reliability',
      what: 'Each prediction gets a light: 🟢 reliable, 🟠 caution, 🔴 out-of-domain, 🔵 informative to measure.',
      why: 'A NIRS model is only reliable on samples resembling those it learned. The color links a diagnostic (domain, uncertainty) to an authorized action.',
      details: 'We combine distance to the known domain (T²/Q) with interval width. Strong "reliability" (validated conformal interval) arrives with the native conformal engine.',
      takeaway: 'Never release a 🔴; a 🔵 is worth measuring.',
      methods: ['applicability domain (T²/Q/kNN)', '→ conformal (coming)'],
    },
  },
} satisfies Record<string, E>;
