// Brand generator for quali-nirs4all.
//
// (1) Canonicalizes the shared nirs4all master brand set inside nirs4all-ui
//     (the shared UI package = the logical home), copied verbatim from the
//     flagship (nirs4all-org). Non-destructive: org keeps its copy.
// (2) Reproduces the SAME glyph as a quali-nirs4all VARIANT recolored to the
//     product accent (indigo #4f46e5 — distinct from the teal/purple/orange/blue
//     siblings), then rasterizes the full asset set (PNG sizes, favicon.ico, og).
// (3) Stages the quali variant into the app's public/brand.
//
// Run: node scripts/gen-brand.mjs   (needs @resvg/resvg-js + png-to-ico devDeps)
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { Resvg } from '@resvg/resvg-js';
import pngToIco from 'png-to-ico';

const ORG = '/home/delete/nirs4all/nirs4all-org/assets/brand/nirs4all';
const UI = '/home/delete/nirs4all/nirs4all-ui/assets/brand';
const NIRS = `${UI}/nirs4all`;          // shared teal master, housed in ui
const QUALI = `${UI}/quali`;            // recolored quali variant
const APP = '/home/delete/nirs4all/nirs4all-quality/app/public/brand';

const MASTER = '#058E96';               // flagship teal token in the SVGs
const ACCENT = '#4F46E5';               // quali-nirs4all accent (indigo)
const PAPER = '#faf7f0';                // warm-paper background (og)

const SVGS = ['icon.svg', 'horizontal.svg', 'horizontal-dark.svg', 'stacked.svg', 'stacked-dark.svg'];

for (const d of [NIRS, QUALI, APP]) mkdirSync(d, { recursive: true });

// (1) shared master → nirs4all-ui/assets/brand/nirs4all (verbatim teal)
for (const f of [...SVGS, 'favicon.ico', 'icon-32.png', 'icon-180.png', 'icon-256.png', 'icon-512.png', 'og.png']) {
  try { copyFileSync(`${ORG}/${f}`, `${NIRS}/${f}`); } catch { /* optional file */ }
}

// (2) quali variant — recolor the accent token in every SVG
const recolor = (s) => s.replaceAll(MASTER, ACCENT).replaceAll(MASTER.toLowerCase(), ACCENT);
for (const f of SVGS) {
  writeFileSync(`${QUALI}/${f}`, recolor(readFileSync(`${ORG}/${f}`, 'utf8')));
}

// rasterize the recolored icon at the ecosystem sizes
const iconSvg = readFileSync(`${QUALI}/icon.svg`, 'utf8');
const renderPng = (svg, width) => new Resvg(svg, { fitTo: { mode: 'width', value: width } }).render().asPng();
const sizes = { 'icon-32.png': 32, 'icon-180.png': 180, 'icon-256.png': 256, 'icon-512.png': 512 };
const pngs = {};
for (const [name, w] of Object.entries(sizes)) {
  pngs[name] = renderPng(iconSvg, w);
  writeFileSync(`${QUALI}/${name}`, pngs[name]);
}

// favicon.ico from 16/32/48 renders
const ico = await pngToIco([renderPng(iconSvg, 16), renderPng(iconSvg, 32), renderPng(iconSvg, 48)]);
writeFileSync(`${QUALI}/favicon.ico`, ico);

// og.png (1200×630) — the recolored wordmark centered on warm paper. The wordmark
// letters are vector <path>s (not <text>), so they render without any font files.
const wordmark = readFileSync(`${QUALI}/horizontal.svg`, 'utf8');
const inner = wordmark.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
// wordmark viewBox is 889.81 × 312; center it on the 1200×630 canvas
const ogSvg =
  `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">` +
  `<rect width="1200" height="630" fill="${PAPER}"/>` +
  `<rect x="0" y="0" width="1200" height="4" fill="${ACCENT}"/>` +
  `<g transform="translate(155,159)">${inner}</g>` +
  `</svg>`;
writeFileSync(`${QUALI}/og.png`, renderPng(ogSvg, 1200));

// README for the quali kit
writeFileSync(`${QUALI}/README.md`,
  `# quali-nirs4all brand assets\n\nQuali-nirs4all variant of the shared nirs4all glyph.\n\nColor: \`${ACCENT}\` (indigo).\n\nSame layout as the ecosystem kit (\`../nirs4all\`, \`../\` = ui blue): \`icon.svg\`, raster icon sizes, \`favicon.ico\`, horizontal + stacked SVG (+ dark), \`og.png\`. Generated by \`nirs4all-quality/app/scripts/gen-brand.mjs\` — recolor the \`ACCENT\` token and re-run to regenerate.\n`);

// (3) stage the quali variant into the app
for (const f of ['icon.svg', 'favicon.ico', 'icon-32.png', 'icon-180.png', 'icon-512.png', 'horizontal.svg', 'horizontal-dark.svg', 'stacked.svg', 'og.png']) {
  copyFileSync(`${QUALI}/${f}`, `${APP}/${f}`);
}

console.log(`✓ brand generated: quali accent ${ACCENT}`);
console.log(`  → ${NIRS} (shared teal master)`);
console.log(`  → ${QUALI} (quali variant + rasters)`);
console.log(`  → ${APP} (app staged)`);
