import { chromium } from 'playwright-core';
const URL = process.env.SMOKE_URL || 'http://localhost:4630/';
const EXE = process.env.CHROME || '/usr/bin/google-chrome';
const b = await chromium.launch({ executablePath: EXE, headless: true, args: ['--no-sandbox'] });
const p = await b.newPage();
await p.setViewportSize({ width: 1200, height: 900 });
await p.goto(URL, { waitUntil: 'load' });
await p.waitForSelector('header img[alt="nirs4all"]');
await p.waitForTimeout(400);
await p.screenshot({ path: '/tmp/qn-projects.png' });
await p.locator('button', { hasText: 'Protéines' }).first().click();
await p.waitForSelector('[data-step-id="select"]');
await p.locator('[data-step-id="select"]').click();
await p.waitForSelector('text=/Score d’information|Information score/');
await p.waitForTimeout(400);
await p.screenshot({ path: '/tmp/qn-select.png', fullPage: true });
await p.locator('[data-step-id="calibrate"]').click();
await p.waitForSelector('text=/Lancer la calibration/');
await p.getByRole('button', { name: /Lancer la calibration/ }).click();
await p.waitForSelector('text=/Classement des pipelines/', { timeout: 90000 });
await p.waitForTimeout(500);
await p.screenshot({ path: '/tmp/qn-calib-board.png', fullPage: true });
await b.close();
console.log('shots done');
